import "~/styles/globals.css";

import { Tinos } from "next/font/google";
import MainLayout from "~/components/common/layout/MainLayout";

const tinos = Tinos({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`font-sans ${tinos.variable} text-body-1 text-zinc-700`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
