import "~/styles/globals.css";

import { Tinos } from "next/font/google";

const tinos = Tinos({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${tinos.variable} bg-neutral-100 text-neutral-900`}>
        {children}
      </body>
    </html>
  );
}
